# DB
services:
  db:
    # image: postgres:14
    build: apps/db/.
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: inventario
    ports: 
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - inventario_network
  
  backend:
    build: apps/backendJava/inventario/.
    # restart: always
    # depends_on: 
    #   - db
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventario
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports: 
      - 8080:8080
    networks:
      - inventario_network


volumes:
  db_data:

networks:
  inventario_network:
    driver: bridge


# backendJava